language: java

sudo: required

services:
  - docker

before_install:
  - docker pull sameersbn/postgresql:9.4-12
  - docker run --name postgresql -itd --restart always --publish 5432:5432 --volume /srv/docker/postgresql:/var/lib/postgresql sameersbn/postgresql:9.4-12
